In [45]:
##ASSIGNMENT##
import numpy as np 
import pandas as pd

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

dataset=pd.read_csv('C:/Users/hp/Desktop/DS assignment 2 - ADR Clasification/Data.csv')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [46]:
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 23516):
    tweet = re.sub('[^a-zA-Z]',' ',dataset['Tweet'][i])
    tweet = tweet.lower()
    tweet = tweet.split()
    port_stem= PorterStemmer()
    tweet = [port_stem.stem(word) for word in tweet if not word in set(stopwords.words('english'))]
    tweet = ' '.join(tweet) 
    corpus.append(tweet)


In [47]:
from sklearn.feature_extraction. text import CountVectorizer
coun_vect = CountVectorizer(max_features = 3000)
X = coun_vect.fit_transform(corpus).toarray() 
y = dataset.iloc[:, 3].values


In [50]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)


In [51]:
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB ()
clf.fit(X_train, y_train)


GaussianNB(priors=None)

In [53]:
 y_pred = clf.predict(X_test)

In [55]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)


In [56]:
conf_mat

array([[1985, 3003],
       [ 166, 1901]], dtype=int64)

In [57]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, clf.predict_proba (X_test)[:,1])


0.6619024022433715

In [59]:
dataset.head

<bound method NDFrame.head of          UserId  TweetId                                              Tweet  \
0      10030778   413205      Intravenous azithromycin-induced ototoxicity.   
1      10048291   528244  Immobilization, while Paget's bone disease was...   
2      10048291   361834  Unaccountable severe hypercalcemia in a patien...   
3      10082597   292240  METHODS: We report two cases of pseudoporphyri...   
4      10082597   467101  METHODS: We report two cases of pseudoporphyri...   
5      10082597   599105  Naproxen, the most common offender, has been a...   
6      10082597   259287  RESULTS: A 44-year-old man taking naproxen for...   
7      10082597   479710  RESULTS: A 44-year-old man taking naproxen for...   
8      10082597   141130  RESULTS: A 44-year-old man taking naproxen for...   
9      10082597   787933  RESULTS: A 44-year-old man taking naproxen for...   
10     10084639   938859  BACKGROUND: How to best treat psychotic patien...   
11     10084639    701

In [65]:
from sklearn.neighbors import KNeighborsClassifier
clf1= KNeighborsClassifier(n_neighbors=3)
clf1.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [66]:
y_pred=clf1.predict(X_test)

In [67]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)

In [68]:
conf_mat

array([[4798,  190],
       [1030, 1037]], dtype=int64)

In [69]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, clf1.predict_proba (X_test)[:,1])

0.8273209840045718

In [70]:
dataset.head

<bound method NDFrame.head of          UserId  TweetId                                              Tweet  \
0      10030778   413205      Intravenous azithromycin-induced ototoxicity.   
1      10048291   528244  Immobilization, while Paget's bone disease was...   
2      10048291   361834  Unaccountable severe hypercalcemia in a patien...   
3      10082597   292240  METHODS: We report two cases of pseudoporphyri...   
4      10082597   467101  METHODS: We report two cases of pseudoporphyri...   
5      10082597   599105  Naproxen, the most common offender, has been a...   
6      10082597   259287  RESULTS: A 44-year-old man taking naproxen for...   
7      10082597   479710  RESULTS: A 44-year-old man taking naproxen for...   
8      10082597   141130  RESULTS: A 44-year-old man taking naproxen for...   
9      10082597   787933  RESULTS: A 44-year-old man taking naproxen for...   
10     10084639   938859  BACKGROUND: How to best treat psychotic patien...   
11     10084639    701

In [74]:
from sklearn.ensemble import RandomForestClassifier
clf3 = RandomForestClassifier(n_estimators=100, max_depth=2,
                              random_state=0)
clf3.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [75]:
y_pred=clf3.predict(X_test)

In [76]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)

In [77]:
conf_mat

array([[4988,    0],
       [2067,    0]], dtype=int64)

In [80]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, clf3.predict_proba (X_test)[:,1])

0.820290661787613

In [81]:
dataset.head

<bound method NDFrame.head of          UserId  TweetId                                              Tweet  \
0      10030778   413205      Intravenous azithromycin-induced ototoxicity.   
1      10048291   528244  Immobilization, while Paget's bone disease was...   
2      10048291   361834  Unaccountable severe hypercalcemia in a patien...   
3      10082597   292240  METHODS: We report two cases of pseudoporphyri...   
4      10082597   467101  METHODS: We report two cases of pseudoporphyri...   
5      10082597   599105  Naproxen, the most common offender, has been a...   
6      10082597   259287  RESULTS: A 44-year-old man taking naproxen for...   
7      10082597   479710  RESULTS: A 44-year-old man taking naproxen for...   
8      10082597   141130  RESULTS: A 44-year-old man taking naproxen for...   
9      10082597   787933  RESULTS: A 44-year-old man taking naproxen for...   
10     10084639   938859  BACKGROUND: How to best treat psychotic patien...   
11     10084639    701

In [82]:
from sklearn.linear_model import LogisticRegression
clf4 = LogisticRegression(random_state=0, solver='lbfgs',
                         multi_class='multinomial').fit(X, y)
clf4.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [83]:
y_pred=clf4.predict(X_test)

In [84]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)

In [85]:
conf_mat

array([[4624,  364],
       [ 524, 1543]], dtype=int64)

In [86]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, clf4.predict_proba (X_test)[:,1])

0.9271057989586231

In [87]:
dataset.head

<bound method NDFrame.head of          UserId  TweetId                                              Tweet  \
0      10030778   413205      Intravenous azithromycin-induced ototoxicity.   
1      10048291   528244  Immobilization, while Paget's bone disease was...   
2      10048291   361834  Unaccountable severe hypercalcemia in a patien...   
3      10082597   292240  METHODS: We report two cases of pseudoporphyri...   
4      10082597   467101  METHODS: We report two cases of pseudoporphyri...   
5      10082597   599105  Naproxen, the most common offender, has been a...   
6      10082597   259287  RESULTS: A 44-year-old man taking naproxen for...   
7      10082597   479710  RESULTS: A 44-year-old man taking naproxen for...   
8      10082597   141130  RESULTS: A 44-year-old man taking naproxen for...   
9      10082597   787933  RESULTS: A 44-year-old man taking naproxen for...   
10     10084639   938859  BACKGROUND: How to best treat psychotic patien...   
11     10084639    701